import smtplib

class Email():
    def __init__(self):
        port = 2525
        smtp_server = "smtp.mailtrap.io"
        login = "1a2b3c4d5e6f7g" # your login generated by Mailtrap
        password = "1a2b3c4d5e6f7g" # your password generated by Mailtrap